//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apallon1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Администрация
    {
        public int код_админа { get; set; }
        public string Фамилия { get; set; }
        public string имя { get; set; }
        public string отчество { get; set; }
        public string пол { get; set; }
        public string Должность { get; set; }
        public Nullable<System.DateTime> Дата_выхода { get; set; }
        public string тэг { get; set; }
        public string код { get; set; }
        public string пароль { get; set; }
    }
}
