//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apallon1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Клиенты
    {
        public int код_клиента { get; set; }
        public string имя { get; set; }
        public string фамилия { get; set; }
        public string отчество { get; set; }
        public string телефон { get; set; }
        public string email { get; set; }
        public string пол { get; set; }
        public string логин { get; set; }
        public string пароль { get; set; }
        public string фото { get; set; }
    }
}
