//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apallon1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Покупка
    {
        public int код_Покупки { get; set; }
        public Nullable<int> код_клиента { get; set; }
        public Nullable<int> код_товара { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<System.DateTime> дата_покупки { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
