//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apallon1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставка
    {
        public int код_поставки { get; set; }
        public Nullable<int> код_поставщика { get; set; }
        public Nullable<int> код_товара { get; set; }
        public Nullable<int> количество { get; set; }
        public Nullable<decimal> цена_поставки { get; set; }
        public Nullable<System.DateTime> дата_поставки { get; set; }
    
        public virtual Поставщик Поставщик { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
