//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apallon1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товар
    {
        public int код_товара { get; set; }
        public string Наименование { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<System.DateTime> Срок_Годности { get; set; }
        public string Описание { get; set; }
    }
}
